services:
  tileserver:
    image: ghcr.io/maplibre/martin:1.4.0
    container_name: map_martin
    restart: always
    volumes:
      - ./map_data/tiles:/tiles:ro
    # 【改动在这里】最新版直接传目录路径，不再需要 --dir
    command: ["/tiles"]
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: map_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./map_data/www:/usr/share/nginx/html:ro
      - ./map_data/fonts:/usr/share/nginx/fonts:ro
    depends_on:
      - tileserver