version: '3.8'

services:
  # 1. 地图引擎容器 (Martin)
  tileserver:
    image: ghcr.io/maplibre/martin:1.4.0
    container_name: map_martin
    restart: always
    volumes:
      # 映射本地 map_data 目录到容器
      - ./map_data:/tiles:ro
    # 修正：Martin 启动参数指向挂载的目录
    command: ["/tiles"]
    ports:
      - "8080:80"    # 宿主机 8080 访问 Nginx
      - "3000:3000"  # 宿主机 3000 直接访问 Martin
      - "2322:2322"  # 宿主机 2322 访问 photon 的调试端口

  photon:
    image: rtuszik/photon-docker:latest
    container_name: map_photon
    restart: always
    network_mode: "service:tileserver" # 加入 Martin 的网络空间 (localhost 共享)
    volumes:
      - ./map_data/photon_data:/photon/photon_data
    command: [
      "java", "-Xmx4g", "-Xms4g",
      "-jar", "/photon/photon.jar",
      "-listen-ip", "0.0.0.0"
    ]
  
  # 代理/认证容器 (Nginx)
  nginx:
    # 建议使用你 build 的那个镜像，或者标准的 nginx:alpine
    image: nginx:alpine 
    container_name: map_nginx
    restart: always
    # 使用 tileserver 的网络，确保 127.0.0.1:3000 能访问到 Martin
    network_mode: "service:tileserver"
    volumes:
      # 挂载配置文件（注意：alpine 默认读取 /etc/nginx/conf.d/default.conf）
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
      # 【关键：对齐 K8s 路径】
      # 将本地整个 map_data 文件夹挂载到 /usr/share/nginx/data
      # 这样你在 nginx.conf 里写的 /usr/share/nginx/data/fonts 等路径在本地也能通
      - ./map_data:/usr/share/nginx/data:ro
      
    depends_on:
      - tileserver